---
# ansible-playbook /etc/ansible/playbooks/cassandra22x/operate_rolling_full_partitioner-range_repair_by_node_for_keyspace_cf.yml --extra-vars "target=ansible_inventory_hosts keyspace_name=keyspace_name columnfamily_name=columnfamily_name"
- hosts: "{{ target | default('FAIL') }}"
  gather_facts: false
  any_errors_fatal: true
  serial: 1
  roles:
    - cassandra22x_operate_repair_full_partitioner-range_by_keyspace_cf